name: Wii-ppc-ra-complete
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Config
      run: |
        git config --global --add safe.directory /__w/beetle-pce-fast-libretro/beetle-pce-fast-libretro
    - name: Compile libretro_wii.a
      run: |
        make -f Makefile platform=wii
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: |
          .
